StylesPath = .vale/styles
MinAlertLevel = error

Packages = Microsoft, Google, Vale

[*.md]
BasedOnStyles = Vale, Microsoft, Google

# Potlačení pravopisu pro české texty (Microsoft a Vale styly)
Microsoft.Spelling = NO
Vale.Spelling = NO
Google.Spelling = NO
