name: Danger
on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger JS
        uses: danger/danger-js@9.1.5 # Fixed version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
