name: MegaLinter
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: MegaLinter
        uses: oxsecurity/megalinter@v7
        env:
          VALIDATE_ALL_CODEBASE: false # Only changed files
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
